# Generated by Django 5.0.1 on 2025-12-26 06:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('BLOUSE', 'Blouse'), ('SAREE', 'Saree'), ('DRESS', 'Dress'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(help_text="Template name (e.g., 'Standard Blouse Template')", max_length=200)),
                ('image', models.ImageField(help_text='Sketch image with measurement points', upload_to='measurement_templates/')),
                ('fields', models.JSONField(default=list, help_text='Measurement field definitions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measurements', models.JSONField(default=dict, help_text='Measurement data as key-value pairs')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='customers.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='measurements.measurementtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='measurementtemplate',
            index=models.Index(fields=['user', 'item_type', '-created_at'], name='measurement_user_id_990383_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['user', 'customer', '-created_at'], name='measurement_user_id_5b5ad7_idx'),
        ),
    ]
