# Generated by Django 5.0.1 on 2026-01-04 12:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(default='My Shop', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_prefix', models.CharField(default='INV/25-26/', max_length=50)),
                ('quotation_prefix', models.CharField(default='QUO/25-26/', max_length=50)),
                ('default_currency', models.CharField(default='INR', max_length=10)),
                ('delivery_duration_days', models.PositiveIntegerField(default=7)),
                ('invoice_numbering_format', models.CharField(default='{prefix}{number}', max_length=100)),
                ('default_tax_type', models.CharField(choices=[('GST', 'GST'), ('NON_GST', 'Non-GST')], default='GST', max_length=20)),
                ('default_cgst_percent', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('default_sgst_percent', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('default_igst_percent', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('show_tax_on_invoice', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shops',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff')], default='owner', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.shop'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.shop')),
            ],
            options={
                'db_table': 'payment_methods',
                'unique_together': {('shop', 'name')},
            },
        ),
    ]
