# Generated by Django 5.0.1 on 2026-01-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shop_user_is_2fa_enabled_user_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='invoice_template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('elegant', 'Elegant')], default='classic', help_text='Invoice PDF template style', max_length=20),
        ),
    ]
