# Generated by Django 5.0.1 on 2026-01-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit', max_digits=10, null=True),
        ),
    ]
