# Generated by Django 5.0.1 on 2026-01-11 10:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_shop_invoice_template'),
        ('orders', '0002_orderitem_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_unit', models.CharField(choices=[('PCS', 'Pieces'), ('MTR', 'Meters'), ('YRD', 'Yards'), ('SET', 'Set'), ('ROLL', 'Roll'), ('SPOOL', 'Spool'), ('KG', 'Kilograms'), ('GM', 'Grams')], default='PCS', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='accounts.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inventory Categories',
                'db_table': 'inventory_categories',
                'ordering': ['name'],
                'unique_together': {('shop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, help_text='Optional SKU/code', max_length=50, null=True)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('MTR', 'Meters'), ('YRD', 'Yards'), ('SET', 'Set'), ('ROLL', 'Roll'), ('SPOOL', 'Spool'), ('KG', 'Kilograms'), ('GM', 'Grams')], default='PCS', max_length=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, help_text='Alert when stock falls below this level', max_digits=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price per unit', max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per unit', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.inventorycategory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='accounts.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of use (copied from inventory item)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_added', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_usages', to='inventory.inventoryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_used', to='orders.order')),
            ],
            options={
                'db_table': 'order_materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('reason', models.CharField(choices=[('PURCHASE', 'Purchase/Restock'), ('ORDER_USAGE', 'Used in Order'), ('DAMAGED', 'Damaged/Waste'), ('RETURNED', 'Customer Return'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('INITIAL_STOCK', 'Initial Stock'), ('ORDER_CANCELLED', 'Order Cancelled')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_changes', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='inventory.inventoryitem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order')),
                ('order_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.ordermaterial')),
            ],
            options={
                'verbose_name_plural': 'Stock History',
                'db_table': 'stock_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['shop', 'is_active', 'is_deleted'], name='inventory_i_shop_id_5d633e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category', 'is_active'], name='inventory_i_categor_f2c5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['shop', 'current_stock'], name='inventory_i_shop_id_719286_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['inventory_item', '-created_at'], name='stock_histo_invento_d56d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['order', '-created_at'], name='stock_histo_order_i_6a17fc_idx'),
        ),
    ]
