# Generated by Django 5.0.1 on 2026-01-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorycategory_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='selling_price',
        ),
    ]
