# Generated by Django 5.0.1 on 2025-12-26 06:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('to_address', models.TextField()),
                ('client_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='INR', max_length=10)),
                ('document_type', models.CharField(choices=[('quotation', 'Quotation'), ('invoice', 'Invoice')], default='invoice', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gpay_phonepe', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_type', models.CharField(blank=True, choices=[('interstate', 'Interstate'), ('intrastate', 'Intrastate')], max_length=20, null=True)),
                ('cgst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sgst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('igst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('items', models.JSONField()),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('share_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('voided', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
