# Generated by Django 5.0.1 on 2025-12-24 17:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_measurement_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='measurement',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='measurements',
            field=models.JSONField(default=dict, help_text='Measurement values as key-value pairs'),
        ),
        migrations.CreateModel(
            name='MeasurementTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('BLOUSE', 'Blouse'), ('SAREE', 'Saree'), ('DRESS', 'Dress'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(help_text="Template name (e.g., 'Standard Blouse Template')", max_length=200)),
                ('image', models.ImageField(help_text='Sketch image with measurement points', upload_to='measurement_templates/')),
                ('fields', models.JSONField(default=list, help_text='Measurement field definitions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item_type', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='invoice.measurementtemplate'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='invoice.measurementtemplate'),
        ),
        migrations.AddIndex(
            model_name='measurementtemplate',
            index=models.Index(fields=['user', 'item_type', '-created_at'], name='invoice_mea_user_id_82e965_idx'),
        ),
    ]
